name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: symbitic/install-cmake@master

      - name: Configure
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug .

      - name: Build
        run: cmake --build build -j 4
